const keyBase = {
  eng: [
    [
      // row 0
      {
        code: "Backquote",
        value: "`",
        valueShift: "~",
        keySpecial: "",
      },
      {
        code: "Digit1",
        value: "1",
        valueShift: "!",
        keySpecial: "",
      },
      {
        code: "Digit2",
        value: "2",
        valueShift: "@",
        keySpecial: "",
      },
      {
        code: "Digit3",
        value: "3",
        valueShift: "#",
        keySpecial: "",
      },
      {
        code: "Digit4",
        value: "4",
        valueShift: "$",
        keySpecial: "",
      },
      {
        code: "Digit5",
        value: "5",
        valueShift: "%",
        keySpecial: "",
      },
      {
        code: "Digit6",
        value: "6",
        valueShift: "^",
        keySpecial: "",
      },
      {
        code: "Digit7",
        value: "7",
        valueShift: "&",
        keySpecial: "",
      },
      {
        code: "Digit8",
        value: "8",
        valueShift: "*",
        keySpecial: "",
      },
      {
        code: "Digit9",
        value: "9",
        valueShift: "(",
        keySpecial: "",
      },
      {
        code: "Digit0",
        value: "0",
        valueShift: ")",
        keySpecial: "",
      },
      {
        code: "Minus",
        value: "-",
        valueShift: "_",
        keySpecial: "",
      },
      {
        code: "Equal",
        value: "=",
        valueShift: "+",
        keySpecial: "",
      },
      {
        code: "Backspace",
        value: "Backspace",
        valueShift: "Backspace",
        keySpecial: "Backspace",
      },
    ],
    //row 1
    [
      {
        code: "Tab",
        value: "Tab",
        valueShift: "Tab",
        keySpecial: "Tab",
      },
      {
        code: "KeyQ",
        value: "q",
        valueShift: "Q",
        keySpecial: "",
      },
      {
        code: "KeyW",
        value: "w",
        valueShift: "W",
        keySpecial: "",
      },
      {
        code: "KeyE",
        value: "e",
        valueShift: "E",
        keySpecial: "",
      },
      {
        code: "KeyR",
        value: "r",
        valueShift: "R",
        keySpecial: "",
      },
      {
        code: "KeyT",
        value: "t",
        valueShift: "T",
        keySpecial: "",
      },
      {
        code: "KeyY",
        value: "y",
        valueShift: "Y",
        keySpecial: "",
      },
      {
        code: "KeyU",
        value: "u",
        valueShift: "U",
        keySpecial: "",
      },
      {
        code: "KeyI",
        value: "i",
        valueShift: "I",
        keySpecial: "",
      },
      {
        code: "KeyO",
        value: "o",
        valueShift: "O",
        keySpecial: "",
      },
      {
        code: "KeyP",
        value: "p",
        valueShift: "P",
        keySpecial: "",
      },
      {
        code: "BracketLeft",
        value: "[",
        valueShift: "{",
        keySpecial: "",
      },
      {
        code: "BracketRight",
        value: "]",
        valueShift: "}",
        keySpecial: "",
      },
      {
        code: "]",
        value: "",
        valueShift: "",
        keySpecial: "",
      },
      {
        code: "Backslash",
        value: "\\",
        valueShift: "|",
        keySpecial: "",
      },
      {
        code: "Delete",
        value: "Delete",
        valueShift: "Delete",
        keySpecial: "Delete",
      },
    ],
    //row 2
    [
      {
        code: "CapsLock",
        value: "CapsLock",
        valueShift: "CapsLock",
        keySpecial: "CapsLock",
      },
      {
        code: "KeyA",
        value: "a",
        valueShift: "A",
        keySpecial: "",
      },
      {
        code: "KeyS",
        value: "s",
        valueShift: "S",
        keySpecial: "",
      },
      {
        code: "KeyD",
        value: "d",
        valueShift: "D",
        keySpecial: "",
      },
      {
        code: "KeyF",
        value: "f",
        valueShift: "F",
        keySpecial: "",
      },
      {
        code: "KeyG",
        value: "g",
        valueShift: "G",
        keySpecial: "",
      },
      {
        code: "KeyH",
        value: "h",
        valueShift: "H",
        keySpecial: "",
      },
      {
        code: "KeyJ",
        value: "j",
        valueShift: "J",
        keySpecial: "",
      },
      {
        code: "KeyK",
        value: "k",
        valueShift: "K",
        keySpecial: "",
      },
      {
        code: "KeyL",
        value: "l",
        valueShift: "L",
        keySpecial: "",
      },
      {
        code: "Semicolon",
        value: ";",
        valueShift: ":",
        keySpecial: "",
      },
      {
        code: "KeyQuote",
        value: "'",
        valueShift: '"',
        keySpecial: "",
      },
      {
        code: "Enter",
        value: "Enter",
        valueShift: "Enter",
        keySpecial: "Enter",
      },
    ],
    //row3
    [
      {
        code: "ShiftLeft",
        value: "Shift",
        valueShift: "Shift",
        keySpecial: "ShiftLeft",
      },
      {
        code: "KeyZ",
        value: "z",
        valueShift: "Z",
        keySpecial: "",
      },
      {
        code: "KeyX",
        value: "x",
        valueShift: "X",
        keySpecial: "",
      },
      {
        code: "KeyC",
        value: "c",
        valueShift: "C",
        keySpecial: "",
      },
      {
        code: "KeyV",
        value: "v",
        valueShift: "V",
        keySpecial: "",
      },
      {
        code: "KeyB",
        value: "b",
        valueShift: "B",
        keySpecial: "",
      },
      {
        code: "KeyN",
        value: "n",
        valueShift: "N",
        keySpecial: "",
      },
      {
        code: "KeyM",
        value: "m",
        valueShift: "M",
        keySpecial: "",
      },
      {
        code: "Comma",
        value: ",",
        valueShift: "<",
        keySpecial: "",
      },
      {
        code: "Period",
        value: ".",
        valueShift: ">",
        keySpecial: "",
      },
      {
        code: "Slash",
        value: "/",
        valueShift: "?",
        keySpecial: "",
      },

      {
        code: "ArrowUp",
        value: "▲",
        valueShift: "▲",
        keySpecial: "",
      },
      {
        code: "ShiftRight",
        value: "Shift",
        valueShift: "Shift",
        keySpecial: "ShiftRight",
      },
    ],
    //row 4
    [
      {
        code: "ControlLeft",
        value: "Ctrl",
        valueShift: "Ctrl",
        keySpecial: "ControlLeft",
      },
      {
        code: "MetaLeft",
        value: "Win",
        valueShift: "Win",
        keySpecial: "Win",
      },
      {
        code: "AltLeft",
        value: "Alt",
        valueShift: "Alt",
        keySpecial: "AltLeft",
      },
      {
        code: "Space",
        value: " ",
        valueShift: " ",
        keySpecial: "",
      },
      {
        code: "AltRight",
        value: "Alt",
        valueShift: "Alt",
        keySpecial: "AltRight",
      },
      {
        code: "ArrowLeft",
        value: "◄",
        valueShift: "◄",
        keySpecial: "",
      },
      {
        code: "ArrowDown",
        value: "▼",
        valueShift: "▼",
        keySpecial: "",
      },
      {
        code: "ArrowRight",
        value: "►",
        valueShift: "►",
        keySpecial: "",
      },
      {
        code: "ControlRight",
        value: "Ctrl",
        valueShift: "Ctrl",
        keySpecial: "ControlRight",
      },
    ],
  ],
};
